site_name: Kimberly's Personal Website
site_url: https://knmcguire.github.io/
theme:
  name: material
  favicon: images/taro_icon.svg
  logo: images/kim_background_white.png
  language: en
  palette: 
    primary: teal
    accent: green
  custom_dir: overrides

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
      categories_allowed:
        - personal
        - builds
        - art
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date.created
        as_update: date.updated


site_dir: _site

not_in_nav: projects/*

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      name: Kimberly on Twitter
      link: https://www.x.com/k_n_mcguire/
    - icon: fontawesome/brands/mastodon
      name: Kimberly on Mastedon
      link: https://fosstodon.org/@k_n_mcguire
    - icon: fontawesome/brands/linkedin
      name: Kimberly on LinkedIn
      link: https://www.linkedin.com/in/knmcguire/
    - icon: fontawesome/brands/github
      name: Kimberly on Github
      link: https://github.com/knmcguire
    - icon: fontawesome/brands/google-scholar
      name: Kimberly on Google Scholar
      link: https://scholar.google.com/citations?hl=en&user=Mu4nP2QAAAAJ
    - icon: fontawesome/brands/researchgate
      name: Kimberly on Research Gate
      link: https://www.researchgate.net/profile/Kimberly-Mcguire-2
    - icon: fontawesome/brands/youtube
      name: Kimberly on Youtube
      link: https://www.youtube.com/channel/UCRPVP3M1cP8aGyS2F_b1vww/playlists
    - icon: fontawesome/solid/rss
      name: Kimberly's blog on RSS
      link: https://knmcguire.github.io/feed_rss_created.xml

copyright: Copyright &copy; 2021 - 2025 Kimberly N. McGuire. Privacy-friendly analytics by Goatcounter
