theme: minima
repository: knmcguire.github.io
title: Robo-Doc
author: Kimberly McGuire
email: kimberleymcguire_at_gmail.com

gems:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

#markdown: kramdown

markdown_extensions:
  - attr_list

header_pages:
  - index.md
  - about.md
  - projects/index.md

twitter_username: k_n_mcguire
github_username: knmcguire
instagram_username: kn_mcguire
linkedin_username: knmcguire


google_analytics: G-XRLS8VMSRB
